config/routes.rb
Rails.application.routes.draw do
  resources :bays do
    get :parked_cars, on: :member
    get :collect_car, on: :member
    get :move_car, on: :member
  end
  resources :cars do
    get :track_all_cars, on: :collection
  end
  root to: "bays#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bay.rb
class Bay < ApplicationRecord
    enum size: {single: 0, double: 1}

    has_many :bays_cars,   dependent: :destroy
    has_many :cars,        through: :bays_cars

    def no_of_parking_cars
        bays_cars.where.not(parked_at: nil).where(left_at: nil).size
    end
end

app/models/bays_car.rb
class BaysCar < ApplicationRecord
    # Relations
    belongs_to :bay,             class_name: "Bay",        foreign_key: :bay_id
    belongs_to :car,             class_name: "Car",        foreign_key: :car_id
end

app/models/car.rb
class Car < ApplicationRecord
    attr_accessor :bay_id
    has_many :bays_cars,   dependent: :destroy
    has_many :bays,        through: :bays_cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bays_controller.rb
class BaysController < ApplicationController
  before_action :set_bay, only: [:show, :edit, :update, :destroy, :parked_cars, :collect_car, :move_car]

  # GET /bays
  # GET /bays.json
  def index
    @bays = Bay.all
  end

  # GET /bays/1
  # GET /bays/1.json
  def show
  end

  # GET /bays/new
  def new
    @bay = Bay.new
  end

  # GET /bays/1/edit
  def edit
  end

  # POST /bays
  # POST /bays.json
  def create
    @bay = Bay.new(bay_params)

    respond_to do |format|
      if @bay.save
        format.html { redirect_to @bay, notice: 'Bay was successfully created.' }
        format.json { render :show, status: :created, location: @bay }
      else
        format.html { render :new }
        format.json { render json: @bay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bays/1
  # PATCH/PUT /bays/1.json
  def update
    respond_to do |format|
      if @bay.update(bay_params)
        format.html { redirect_to @bay, notice: 'Bay was successfully updated.' }
        format.json { render :show, status: :ok, location: @bay }
      else
        format.html { render :edit }
        format.json { render json: @bay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bays/1
  # DELETE /bays/1.json
  def destroy
    @bay.destroy
    respond_to do |format|
      format.html { redirect_to bays_url, notice: 'Bay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def parked_cars
    @bays_cars = @bay.bays_cars.where.not(parked_at: nil).where(left_at: nil).includes(:car).order(:parked_at)
  end

  def collect_car
    bay_car = @bay.bays_cars.find(params['bay_car_id'])
    if @bay.size == 'double' && @bay.no_of_parking_cars == 2
      new_bay_car = @bay.bays_cars.where.not(parked_at: nil, id: params['bay_car_id']).where(left_at: nil).first
      if bay_car.parked_at < new_bay_car.parked_at
        flash[:notice] = "You have to move the second car first!"
        redirect_to action: 'parked_cars', id: @bay.id and return
      end
    end
    bay_car.update(left_at: Time.now)
    @bay.update(is_available: true)
    no_of_hours = ((Time.now - bay_car.parked_at) / 1.hour).ceil
    fees = 10 * no_of_hours
    flash[:notice] = "Car was successfully collected. Your fees for #{no_of_hours} parking hours is $#{fees}"
    redirect_to action: "index"
  end

  def move_car
    bay_car = @bay.bays_cars.find(params['bay_car_id'])
    new_bay = Bay.where(is_available: true).first
    if new_bay.present?
      bay_car.update(left_at: Time.now)
      new_bay.cars << bay_car.car
      new_bay.update(is_available: false) if (new_bay.size == 'single' && new_bay.bays_cars.where(left_at: nil).size == 1) || ((new_bay.size == 'double' && new_bay.bays_cars.where(left_at: nil).size == 2))
      new_bay.bays_cars.find_by(car_id: bay_car.car.id).update(parked_at: bay_car.parked_at)
      @bay.update(is_available: true)
      flash[:notice] = "car successfully moved to bay #{new_bay.number}"
      redirect_to action: 'parked_cars', id: @bay.id
    else
      flash[:notice] = "no vacant bays"
      redirect_to action: 'parked_cars', id: @bay.id
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bay
      @bay = Bay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bay_params
      bp = params.require(:bay).permit(:number, :size, :is_available)
      bp[:size] = params[:bay][:size].to_i
      bp
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    if @car.save
      bay = Bay.find(car_params['bay_id'])
      bay.cars << @car
      bay.update(is_available: false) if (bay.size == 'single' && bay.bays_cars.where(left_at: nil).size == 1) || ((bay.size == 'double' && bay.bays_cars.where(left_at: nil).size == 2))
      bay.bays_cars.find_by(car_id: @car.id).update(parked_at: Time.now)
      flash[:notice] = 'Car was successfully parked.'
      redirect_to :controller => 'bays'
    else
      render :new
    end
  end

  def track_all_cars
    @cars = BaysCar.includes(:car).where.not(parked_at: nil).where(left_at: nil).order(:parked_at)
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :owner, :plate_no, :bay_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bays_helper.rb
module BaysHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/bays/_form.html.erb
<%= form_with(model: bay, local: true) do |form| %>
  <% if bay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bay.errors.count, "error") %> prohibited this bay from being saved:</h2>

      <ul>
      <% bay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :is_available %>
    <%= form.check_box :is_available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bays/edit.html.erb
<h1>Editing Bay</h1>

<%= render 'form', bay: @bay %>

<%= link_to 'Show', @bay %> |
<%= link_to 'Back', bays_path %>

app/views/bays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bays</h1>

<table border="1|0" width="60%">
  <thead>
    <tr>
      <th>Number</th>
      <th>Size</th>
      <th>Is Vacant?</th>
      <th>No of Parking Cars</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @bays.each do |bay| %>
      <tr>
        <td><%= bay.number %></td>
        <td><%= bay.size %></td>
        <td><%= bay.is_available ? 'Yes' : 'No' %></td>
        <td><%= link_to "#{bay.no_of_parking_cars}", parked_cars_bay_path(bay.id) %></td>
        <td><%= link_to 'Show', bay %></td>
        <td><%= link_to 'Edit', edit_bay_path(bay) %></td>
        <td><%= link_to 'Delete', bay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if bay.is_available %>
          <td><%= link_to 'Park Car', new_car_path(bay_id: bay.id) %></td>
        <% else %>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bay', new_bay_path %>

<br>

<%= link_to 'Track all Parking Cars', track_all_cars_cars_path %>

app/views/bays/new.html.erb
<h1>New Bay</h1>

<%= render 'form', bay: @bay %>

<%= link_to 'Back', bays_path %>

app/views/bays/parked_cars.html.erb
<p id="notice"><%= notice %></p>

<h1>Parked Cars</h1>

<table border="1|0" width="60%">
  <thead>
    <tr>
      <th>Model</th>
      <th>Owner Name</th>
      <th>Plate Number</th>
      <th>Parked At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bays_cars.each_with_index do |bay_car, i| %>
      <tr>
        <td><%= bay_car.car.model %></td>
        <td><%= bay_car.car.owner %></td>
        <td><%= bay_car.car.plate_no %></td>
        <td><%= bay_car.parked_at.strftime("%d/%m/%Y %I:%M:%S %p") %></td>
        <td>
            <%= link_to 'Collect', collect_car_bay_path(@bay.id, bay_car_id: bay_car.id) %>
            <% if @bays_cars.size > 1 && i == @bays_cars.size - 1 %>
                <%= link_to 'Move', move_car_bay_path(@bay.id, bay_car_id: bay_car.id) %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', bays_path %>

app/views/bays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @bay.number %>
</p>

<p>
  <strong>Size:</strong>
  <%= @bay.size %>
</p>

<p>
  <strong>Is available:</strong>
  <%= @bay.is_available %>
</p>

<%= link_to 'Edit', edit_bay_path(@bay) %> |
<%= link_to 'Back', bays_path %>

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :plate_no %>
    <%= form.number_field :plate_no %>
  </div>

  <%= form.hidden_field :bay_id, :value => bay_id %>

  <div class="actions">
    <%= form.submit "Park Car" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table border="1|0">
  <thead>
    <tr>
      <th>Model</th>
      <th>Owner</th>
      <th>Plate Number</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.owner %></td>
        <td><%= car.plate_no %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cars/new.html.erb
<h1>Park Car</h1>

<%= render 'form', car: @car, bay_id: params[:bay_id] %>

<%= link_to 'Back', bays_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @car.owner %>
</p>

<p>
  <strong>Plate no:</strong>
  <%= @car.plate_no %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/cars/track_all_cars.html.erb
<h1>Cars</h1>

<table border="1|0" width='60%'>
  <thead>
    <tr>
      <th>Model</th>
      <th>Owner</th>
      <th>Plate Number</th>
      <th>Parked At </th>
      <th>Bay No</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.car.model %></td>
        <td><%= car.car.owner %></td>
        <td><%= car.car.plate_no %></td>
        <td><%= car.parked_at.strftime("%d/%m/%Y %I:%M:%S %p") %></td>
        <td><%= car.bay.number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', bays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ValetParkingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>